#!/usr/bin/env python3

import pathlib
import random
import csv

global studentLineCSV

config = (pathlib.Path(__file__).parent / ".config").read_text()
level = int(config)

def get_random_line(afile):
    """Return a random line from the file (or default)."""
    line = ''
    for i, aline in enumerate(afile, start=1):
        if random.randrange(i) == 0:  # random int [0..i)
            line = aline
    return line

def readans(str):
    return str.strip()

with open("/flag") as f:
    global flag
    random.seed(f.read())
    flag = str(f.read())

datasetfname = (pathlib.Path(__file__).parent / "dataset.csv")

with open(datasetfname) as csvfile:
    global studentLineCSV
    studentLineCSV = str(get_random_line(csvfile))

def wordCount(word):
    datasetfname = (pathlib.Path(__file__).parent / "dataset.csv")
    with open(datasetfname) as csvfile:
         csvfile = csvfile.read()     
         return csvfile.count(word)


def level1():
    global studentLineCSV
    print("level1")
    studentLineArray = studentLineCSV.split(',')
    print(studentLineCSV)
    val = input("what borough did the accident on "+studentLineArray[1]+" at "+studentLineArray[2]+" take place?")
    if val == studentLineArray[3]:
        print("Correct: get your flag {flag}")
    else:
        print("try again")

def level2():
    global studentLineCSV
    print("level2") 
    studentLineArray = studentLineCSV.split(',')
    print(str(wordCount(studentLineArray[3]))+" is the answer")
    val = input("how many times does "+studentLineArray[3]+" appear in the doc?")
    if int(val) == int(wordCount(studentLineArray[3])):
        print("Correct: get your flag {flag}")
    else:
        print("try again")

#how many rows share the year?
def level3():
    print("level3")
    global studentLineCSV
    datasetfname = (pathlib.Path(__file__).parent / "dataset.csv")
    studentLineArray = studentLineCSV.split(',')
    count = 0 
    date = studentLineArray[1]
    date = date[-4:]
    with open(datasetfname) as csvfile:
        readerObj = csv.reader(csvfile)
        for row in readerObj:
            rowString = row[1]
            if date in rowString:
                count += 1

    print("the answer is "+ str(count)) 
    val = input("how many rows share the same date as "+studentLineArray[1]+" ?")
   
    if int(val) == count:
        print("Correct: get your flag {flag}")
    else:
        print("try again")

def level4():
    print("level4")
    global studentLineCSV
    datasetfname = (pathlib.Path(__file__).parent / "dataset.csv")
    studentLineArray = studentLineCSV.split(',')
    count = 0 
    date = studentLineArray[1]
    date = date[-4:]
    city = studentLineArray[3]
    with open(datasetfname) as csvfile:
        readerObj = csv.reader(csvfile)
        for row in readerObj:
           rowString = row[1]
           if date in rowString:
               if city in row[3]:
                   count += 1  
    
    print("the answer is "+str(count))
    val = input("how many rows have the same date and same city?")
    if int(val) == count:
        print("Correct: get your flag {flag}")
    else:
        print("try again")

def level5():
    print("level 5")
    global studentLineCSV
    datasetfname = (pathlib.Path(__file__).parent / "dataset.csv")
    studentLineArray = studentLineCSV.split(',')
    count = 0 
    date = studentLineArray[1]
    date = date[-4:]
    with open(datasetfname) as csvfile:
        readerObj = csv.reader(csvfile)
        for row in readerObj:
            rowString = row[1]
            if date not in rowString:
                count += 1
   
    val =input("how many rows do NOT have the following date "+ studentLineArray[1]+" ?")
    if int(val) == count:
        print("Correct: get your flag {flag}")
    else:
        print("try again")

            
def level6():
    datasetfname = (pathlib.Path(__file__).parent / "dataset.csv")
    global studentLineCSV
    studentLineArray = studentLineCSV.split(',')
    print(studentLineArray[0])
    if int(studentLineArray[0]) > 5:
        randNum = int(studentLineArray[0]) // 2
    else:
        randNum = int(studentLineArray[0]) + 264
    with open(datasetfname) as csvfile:
        readerObj = csv.reader(csvfile)
        rows = list(readerObj)
        targetRow = rows[randNum]
    
    print(targetRow[1])
    val = input("which row has "+targetRow[1]+" as the date "+targetRow[2]+" as the time "+targetRow[3]+ " as the borough?")    
    if val == targetRow[0]:
        print("Correct: get your flag {flag}")
    else:
        print("try again")
    
def level7():
    datasetfname = (pathlib.Path(__file__).parent / "dataset.csv")
    global studentLineCSV
    studentLineArray = studentLineCSV.split(',')
    print(studentLineArray[2])
    time = studentLineArray[2]
    print(time[:3])
    time = time[:3]
    count = 0
    with open (datasetfname) as csvfile:
        readerObj = csv.reader(csvfile)
        for row in readerObj:
            if time in row[2]:
                count += 1   
            
    val = input("how many rows are in the same hour as "+studentLineArray[2]+"?")
    if val == count:
        print("Correct: get your flag {flag}")
    else:
        print("try again")

def level8():
    datasetfname = (pathlib.Path(__file__).parent / "dataset.csv")
    global studentLineCSV
    studentLineArray = studentLineCSV.split(',')
    print(studentLineArray)
    date = studentLineArray[1]
    print(date)    
    print(date[2:6])
    date = date[2:6]
    count = 0
    with open (datasetfname) as csvfile:
        readerObj = csv.reader(csvfile)
        for row in readerObj:
            if date in row[1]:
                count += 1
                print(row[1])
    val = input("How many accidents took place on the "+str(date[1:3])+" (st/th) ?")
    if val == count:
        print("Correct: get your flag {flag}")
    else:
        print("try again")


def challenge():
    lvls = {
       1: level1,
       2: level2,
       3: level3,
       4: level4,
       5: level5,
       6: level6,
       7: level7,
       8: level8,
    }
    f = lvls[level]
    f()

challenge()
